web/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins
  devise_for :users

  resources :hosts 
  resources :services
  resources :interfaces
  root 'home#index'

end

web/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

web/app/models/host.rb
class Host < ActiveRecord::Base
    has_many :services
    has_many :interfaces
    accepts_nested_attributes_for :services, allow_destroy: true
    accepts_nested_attributes_for :interfaces, allow_destroy: true
end

web/app/models/interface.rb
class Interface < ActiveRecord::Base
  belongs_to :host
end

web/app/models/service.rb
class Service < ActiveRecord::Base
    belongs_to :host
end

web/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

web/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    	@hosts = Host.all
    	@services = Service.all
    	@interfaces = Interface.all
    end
end

web/app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
    2.times {@host.interfaces.build}
    2.times {@host.services.build}
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      #params.fetch(:host, {})
      params.require(:host).permit(:name, interfaces_attributes: [:name, :ip], services_attributes: [:name])
    end
end

web/app/controllers/interfaces_controller.rb
class InterfacesController < ApplicationController
  before_action :set_interface, only: [:show, :edit, :update, :destroy]

  # GET /interfaces
  # GET /interfaces.json
  def index
    @interfaces = Interface.all
  end

  # GET /interfaces/1
  # GET /interfaces/1.json
  def show
  end

  # GET /interfaces/new
  def new
    @interface = Interface.new
  end

  # GET /interfaces/1/edit
  def edit
  end

  # POST /interfaces
  # POST /interfaces.json
  def create
    @interface = Interface.new(interface_params)

    respond_to do |format|
      if @interface.save
        format.html { redirect_to @interface, notice: 'Interface was successfully created.' }
        format.json { render :show, status: :created, location: @interface }
      else
        format.html { render :new }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interfaces/1
  # PATCH/PUT /interfaces/1.json
  def update
    respond_to do |format|
      if @interface.update(interface_params)
        format.html { redirect_to @interface, notice: 'Interface was successfully updated.' }
        format.json { render :show, status: :ok, location: @interface }
      else
        format.html { render :edit }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interfaces/1
  # DELETE /interfaces/1.json
  def destroy
    @interface.destroy
    respond_to do |format|
      format.html { redirect_to interfaces_url, notice: 'Interface was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interface
      @interface = Interface.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interface_params
      #params.fetch(:interface, {})
      params.require(:interface).permit(:name, :ip)
    end
end

web/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      #params.fetch(:service, {})
      params.require(:service).permit(:name)
    end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/home_helper.rb
module HomeHelper
end

web/app/helpers/hosts_helper.rb
module HostsHelper
end

web/app/helpers/interfaces_helper.rb
module InterfacesHelper
end

web/app/helpers/services_helper.rb
module ServicesHelper
end

web/app/views/home/index.html.erb
<div class="container">
	<div class="col-md-12">
		<% @hosts.each do |host| %>
			<div class="panel panel-primary">
				<div class="panel-heading">Host : <%= host.name %></div>
				<% if !host.interfaces.empty? %>
					<table class="table">
						<tr	>
							<th class="col-md-4 col-sm-4">Interface Name</th>
							<th class="col-md-4 col-sm-4">Ip Address</th>
							<th class="col-md-4 col-sm-4">Status</th>
						</tr>
						<% host.interfaces.each do |interface| %>
							<tr
								<% if interface.status == "up" %>
									class="success"
								<% else %>
									class="danger"
								<% end %>
							>
								<td class="col-md-4 col-sm-4"><%= interface.name %></td>
								<td class="col-md-4 col-sm-4"><%= interface.ip %></td>
								<td class="col-md-4 col-sm-4"><%= interface.status %></td>
							</tr>
						<% end %>
					</table>
				<% end %>
				<% if !host.services.empty? %>
					<table class="table">
						<tr>
							<th class="col-md-4 col-sm-4">Service Name</th>
							<th class="col-md-4 col-sm-4">Infos</th>
							<th class="col-md-4 col-sm-4">Status</th>
						</tr>
						<% host.services.each do |service| %>
							<tr
								<% if service.status == "up" %>
									class="success"
								<% else %>
									class="danger"
								<% end %>
							>
								<td class="col-md-4 col-sm-4"><%= service.name %></td>
								<td class="col-md-4 col-sm-4"><%= service.infos %></td>
								<td class="col-md-4 col-sm-4" ><%= service.status %></td>
							</tr>
						<% end %>
					</table>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

web/app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/hosts/edit.html.erb
<div class="container">
	<div class="col-md-12">
		<h1>Editing Host</h1>
	</div>

	<div class="col-md-12">
		<%= form_for @host do |f| %>
			<%= f.label :name %>:
			<%= f.text_field :name %>

			<%= f.submit %>
		<% end %>
	</div>

	<div class="col-md-12">
		<%= link_to 'Show', @host, :class => 'btn btn-primary', :role => 'button' %>
		<%= link_to 'Back', hosts_path, :class => 'btn btn-default', :role => 'button' %>
	</div>
</div>

web/app/views/hosts/index.html.erb
<div class="container">
	<div class="col-md-12">
		<h1 class="well">Listing Hosts</h1>
	</div>

	<div class="col-md-12">
		<table class="table">
			<thead>
				<tr>
					<th class="col-md-6">Name</th>
					<th class="col-md-6">Actions</th>
				</tr>
			</thead>

			<tbody>
				<% @hosts.each do |host| %>
					<tr>
						<td class="col-md-8"><%= host.name %></td>
						<td class="col-md-4">
							<%= link_to 'Show', host, :class => 'btn btn-info' %>
							<%#= link_to 'Edit', edit_host_path(host), :class => 'btn btn-success' %>
							<%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'  %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>

<!-- 	<div class="col-md-12">
		<%= link_to 'New Host', new_host_path, :class => 'btn btn-primary', :role => 'button' %>
	</div> -->
</div>

web/app/views/hosts/new.html.erb
<div class="container">
	<div class="col-md-12">
		<h1>New Host</h1>
	</div>

	<div class="col-md-12">
		<%= form_for @host do |f| %>
			<%= f.label :name %>:
			<%= f.text_field :name %>
			<ul>
			<%= f.fields_for :interfaces do |interfaces_form| %>
				<li>
			    <%= interfaces_form.label :name %>
			    <%= interfaces_form.text_field :name %>
			    <%= interfaces_form.label :ip %>
			    <%= interfaces_form.text_field :ip %>
			    </li>
			<% end %>
			</ul>
			<ul>
			<%= f.fields_for :services do |services_form| %>
				<li>
			    <%= services_form.label :name %>
			    <%= services_form.text_field :name %>
			    </li>
			<% end %>
			</ul>
			<%= f.submit %>
		<% end %>
	</div>

	<div class="col-md-12">
		<%= link_to 'Back', hosts_path, :class => 'btn btn-default', :role => 'button' %>
	</div>
</div>

web/app/views/hosts/show.html.erb
<div class="container">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-heading">Host : <%= @host.name %></div>
			<% if !@host.interfaces.empty? %>
				<table class="table">
					<tr	>
						<th class="col-md-4 col-sm-4">Interface Name</th>
						<th class="col-md-4 col-sm-4">Ip Address</th>
						<th class="col-md-4 col-sm-4">Status</th>
					</tr>
					<% @host.interfaces.each do |interface| %>
						<tr
							<% if interface.status == "up" %>
								class="success"
							<% else %>
								class="danger"
							<% end %>
						>
							<td class="col-md-4 col-sm-4"><%= interface.name %></td>
							<td class="col-md-4 col-sm-4"><%= interface.ip %></td>
							<td class="col-md-4 col-sm-4"><%= interface.status %></td>
						</tr>
					<% end %>
				</table>
			<% end %>
			<% if !@host.services.empty? %>
				<table class="table">
					<tr>
						<th class="col-md-4 col-sm-4">Service Name</th>
						<th class="col-md-4 col-sm-4">Infos</th>
						<th class="col-md-4 col-sm-4">Status</th>
					</tr>
					<% @host.services.each do |service| %>
						<tr
							<% if service.status == "up" %>
								class="success"
							<% else %>
								class="danger"
							<% end %>
						>
							<td class="col-md-4 col-sm-4"><%= service.name %></td>
							<td class="col-md-4 col-sm-4"><%= service.infos %></td>
							<td class="col-md-4 col-sm-4" ><%= service.status %></td>
						</tr>
					<% end %>
				</table>
			<% end %>
		</div>
	</div>
</div>

web/app/views/interfaces/_form.html.erb
<%= form_for(@interface) do |f| %>
  <% if @interface.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interface.errors.count, "error") %> prohibited this interface from being saved:</h2>

      <ul>
      <% @interface.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/interfaces/edit.html.erb
<div class="container">
	<div class="col-md-12">
		<h1>Editing Interface</h1>
	</div>

	<div class="col-md-12">
		<%= form_for @interface do |f| %>
			<%= f.label :name %>:
			<%= f.text_field :name %>
			<%= f.label :ip %>:
			<%= f.text_field :ip %>

			<%= f.submit %>
		<% end %>
	</div>

	<div class="col-md-12">
		<%= link_to 'Show', @interface, :class => 'btn btn-primary', :role => 'button' %>
		<%= link_to 'Back', interfaces_path, :class => 'btn btn-default', :role => 'button' %>
	</div>
</div>

web/app/views/interfaces/index.html.erb
<div class="container">
  <div class="col-md-12">
    <h1 class="well">Listing Interfaces</h1>
  </div>

  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th class="col-md-4">Name</th>
          <th class="col-md-4">IP</th>
          <th class="col-md-4">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @interfaces.each do |interface| %>
          <tr>
            <td class="col-md-4"><%= interface.name %></td>
            <td class="col-md-4"><%= interface.ip %></td>
            <td class="col-md-4">
              <%= link_to 'Show', interface, :class => 'btn btn-info' %>
              <%= link_to 'Edit', edit_interface_path(interface), :class => 'btn btn-success' %>
              <%= link_to 'Destroy', interface, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'  %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-12">
    <%= link_to 'New Interfaces', new_interface_path, :class => 'btn btn-primary', :role => 'button' %>
  </div>
</div>

web/app/views/interfaces/new.html.erb
<div class="container">
	<div class="col-md-12">
		<h1>New Interface</h1>
	</div>

	<div class="col-md-12">
		<%= form_for @interface do |f| %>
			<%= f.label :name %>:
			<%= f.text_field :name %>
			<%= f.label :ip %>:
			<%= f.text_field :ip %>

			<%= f.submit %>
		<% end %>
	</div>

	<div class="col-md-12">
		<%= link_to 'Back', interfaces_path, :class => 'btn btn-default', :role => 'button' %>
	</div>
</div>

web/app/views/interfaces/show.html.erb
<div class="container">
	<div class="col-md-12">
		<p>Name : <%= @interface.name %></p>
		<p>IP : <%= @interface.ip %></p>
	</div>

	<div class="col-md-12">
		<%= link_to 'Edit', edit_interface_path(@interface), :class => 'btn btn-primary', :role => 'button' %>
		<%= link_to 'Back', interfaces_path, :class => 'btn btn-default', :role => 'button' %>
	</div>
</div>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monitoring</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>

	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">Monitoring</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="<%= 'active' if params[:controller] == 'hosts' %>"><a href="<%= hosts_path %>">Hosts</a></li>
<!-- 					<li class="<%= 'active' if params[:controller] == 'interfaces' %>"><a href="<%= interfaces_path %>">Interfaces</a></li>
					<li class="<%= 'active' if params[:controller] == 'services' %>"><a href="<%= services_path %>">Services</a></li> -->
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		<div class="col-md-12">
			<div
				<% if notice != nil %>
					class="alert alert-info" role="alert"
				<% end %>
			><%= notice %></div>
			<div 
				<% if alert != nil %>
					class="alert alert-danger" role="alert"
				<% end %>
			><%= alert %></div>
		</div>
	</div>

	<%= yield %>


</body>
</html>

web/app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/services/edit.html.erb
<div class="container">
	<div class="col-md-12">
		<h1>Editing Services</h1>
	</div>

	<div class="col-md-12">
		<%= form_for @service do |f| %>
			<%= f.label :name %>:
			<%= f.text_field :name %>

			<%= f.submit %>
		<% end %>
	</div>

	<div class="col-md-12">
		<%= link_to 'Show', @service, :class => 'btn btn-primary', :role => 'button' %>
		<%= link_to 'Back', services_path, :class => 'btn btn-default', :role => 'button' %>
	</div>
</div>

web/app/views/services/index.html.erb
<div class="container">
  <div class="col-md-12">
    <h1 class="well">Listing Services</h1>
  </div>

  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th class="col-md-6">Name</th>
          <th class="col-md-6">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @services.each do |service| %>
          <tr>
            <td class="col-md-6"><%= service.name %></td>
            <td class="col-md-6">
              <%= link_to 'Show', service, :class => 'btn btn-info' %>
              <%= link_to 'Edit', edit_service_path(service), :class => 'btn btn-success' %>
              <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'  %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-12">
    <%= link_to 'New Services', new_service_path, :class => 'btn btn-primary', :role => 'button' %>
  </div>
</div>

web/app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

web/app/views/services/show.html.erb
<div class="container">
	<div class="col-md-12">
		<p>Name : <%= @service.name %></p>
	</div>

	<div class="col-md-12">
		<%= link_to 'Edit', edit_service_path(@service), :class => 'btn btn-primary', :role => 'button' %>
		<%= link_to 'Back', services_path, :class => 'btn btn-default', :role => 'button' %>
	</div>
</div>